title: Coding Intelligence
description: Solving problems in AI, ML, and CV
author: Mustafa Khandwawala
github: https://github.com/kovarn
about: I am a freelance computer science researcher and developer. Currently working on Machine learning and Computer vision problems.
# disqus_shortname: 
# google_analytics: 

enableTags: true
tagarray: []

collections:
  project:
    output: false
    permalink: /project/:path/

# social:
#     - icon: fa-facebook
#       link: "#"
#     - icon: fa-skype
#       link: "#"
#     - icon: fa-twitter
#       link: "#"
#     - icon: fa-linkedin
#       link: "#"
#     - icon: fa-stack-exchange
#       link: "#"

# share:
#   twitter_username: 
#   fb_appid: 

urls:
    - text: About Me
      url: /about/
#     - text: Projects
#       url: /projects/
    - text: Github
      url: https://github.com/kovarn
    - text: XML Feed
      url: /feed.xml

url: "https://kovarn.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist